import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Home from "./lading"; // ¿Quizás querías decir "./landing"?
import ParticlesBackground from './ParticlesBack';

const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-fira-code',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Recomiendo personalizar estos valores:
  // title: "Mi Sitio Web",
  // description: "Descripción única de mi proyecto"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={firaCode.variable}>
      <body>
        {/* Fondo de partículas que cubre toda la pantalla */}
        <div className="fixed inset-0 -z-10">
          <ParticlesBackground />
        </div>
        
        {/* Contenido principal */}
        <main className="relative z-10 min-h-screen">
          {children}
          {/* Si necesitas el componente Home, deberías incluirlo aquí:
              <Home /> */}
        </main>
      </body>
    </html>
  );
}